name: Test and create Docker image for develop branch

on:
  push:
    branches:
    - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --file pom.xml clean install
  build-docker-image:
    needs: test
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - name: Build and publish Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: hsldevcom/transitdata-gtfsrt-full-publisher
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        tags: develop
